version: "3"
services:
  nestjs-api:
    build:
      context: ./nest_api
    container_name: nest_api
    restart: "always"
    depends_on:
      - api_db
    volumes:
      - /nest_api/node_modules
      - ./nest_api/src:/user/src/api/src
    env_file:
      - .env
    ports:
      - "3000:3000"
    networks:
      - pics-network

  api_db:
    image: mongo:latest
    container_name: api_db
    volumes:
      - mongodb:/data/db
    networks:
      - pics-network


networks:
  pics-network:
    driver: bridge

volumes:
  mongodb: